steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/micro-cicd-lab-2505/microservices-repo/service-a:latest', './service-a']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/micro-cicd-lab-2505/microservices-repo/service-b:latest', './service-b']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/micro-cicd-lab-2505/microservices-repo/service-a:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/micro-cicd-lab-2505/microservices-repo/service-b:latest']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/dev/service-a-deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=microservices-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/dev/service-b-deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=microservices-cluster'
